rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0

branches:
  only:
    - master

gemfile:
  - gemfiles/rails_2.3.gemfile
  - gemfiles/rails_3.0.gemfile
  - gemfiles/rails_3.1.gemfile
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile

matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_2.3.gemfile
